
# App to define new GPS device and annual configuration
shinyUI(
  navbarPage("IE Gardouch: ",
             tabPanel("Registre des entrées/sorites",  
                      fluidRow(
                        shinyjs::useShinyjs(),
                        shinyjs::inlineCSS(appCSS),
                        shinyalert::useShinyalert(),
                        column(2,selectInput(inputId ="login", label =labelMandatory("Utilisateur"), choices =c("","Nicolas Cebe","Arnaud Bonnet","Jean-Luc Rames","Marie-Line Maublanc","Hélène Verheyden"))),
                        column(12),
                        column(width= 1,numericInput(inputId = "ani_n_inra", label = labelMandatory("N° de l'animal"), value = dbGetQuery(con,"select max(ani_n_inra) from registre_gardouch")+1, min =1, max = 99999, step = 1),style = "margin-top:25px;"),
                        bsTooltip("ani_n_inra", "par défaut prochain n°Inrae disponible, si vous souhaiter corriger les informations d'un animal existant tapez ici son n°Inrae","bottom", options = list(container = "body")),
                        column(width= 1,textInput(inputId = "ani_nom_registre", label = labelMandatory("Nom"), value = paste0(dbGetQuery(con,"select max(ani_n_inra) from registre_gardouch")+1,"_")),style = "margin-top:25px;"),
                        bsTooltip("ani_nom_registre", "Le nom doit être unique","bottom", options = list(container = "body")),
                        column(width= 1,textInput(inputId = "ani_sexe", label = labelMandatory("Sexe")),style = "margin-top:25px;"),
                        bsTooltip("ani_sexe", "accepte M, m, F ou f","bottom", options = list(container = "body")),
                        column(width= 1,dateInput(inputId = "ani_naissance_date", label = "Date naissance précise", value =  NA),style = "margin-top:5px;"),
                        bsTooltip("ani_naissance_date", "Date de naissance si elle est connue précisément","bottom", options = list(container = "body")),
                        column(width= 1,textInput(inputId = "ani_naissance_txt", label = "Date naissance textuelle"),style = "margin-top:5px;"),
                        bsTooltip("ani_naissance_txt", "Champ textuel à utiliser si la date ne peut être données au format jour/mois/année ","bottom", options = list(container = "body")),
                        column(width= 1,numericInput(inputId = "ani_naissance_entier", label = "Année naissance", value = "", min =2000, max = 2034, step = 1),style = "margin-top:25px;"),
                        bsTooltip("ani_naissance_entier", "A remplir si seule l\\'année de naissance est connue (format YYYY)","bottom", options = list(container = "body")),
                        column(width= 1,checkboxInput(inputId = "ani_local", label = labelMandatory("De Gardouch?")),style = "margin-top:45px;"),
                        bsTooltip("ani_local", "L\\'animal est il né à Gardouch \\?","bottom", options = list(container = "body")),
                        column(width= 1,textInput(inputId = "ani_vient_de", label = labelMandatory("Provenance")),style = "margin-top:25px;"),
                        bsTooltip("ani_vient_de", "Origine de l\\'animal si il n'est pas né à Gardouch","bottom", options = list(container = "body")),
                        column(width= 1,selectInput(inputId = "ani_pere", label = "Père",choices = append("",utf8(dbGetQuery(con,"select ani_nom_registre males from registre_gardouch where ani_sexe = 'M'"))[,1]),selected =""),style = "margin-top:25px;"),
                        bsTooltip("ani_pere", "Nom du père si il est connu","bottom", options = list(container = "body")),
                        column(width= 1,selectInput(inputId = "ani_mere", label = "Mère",choices =append("",utf8(dbGetQuery(con,"select ani_nom_registre femelles from registre_gardouch where ani_sexe = 'F'"))[,1]),selected =""),style = "margin-top:25px;"),
                        bsTooltip("ani_mere", "Nom de la mère si elle est connue","bottom", options = list(container = "body")),
                        column(width= 1,numericInput(inputId = "ani_taille_porte", label = "Taille de la portée", value = "", min =1, max = 4, step = 1),style = "margin-top:25px;"),
                        bsTooltip("ani_mere", "Taille de portée à laquelle appartient cet animal","bottom", options = list(container = "body")),
                        column(width= 1,selectInput(inputId = "ani_espece_id", label = labelMandatory("Espèce"),choices =dbGetQuery(con,"SELECT distinct(obj_name) FROM list.tr_object_obj where obj_animal = TRUE;")[,1], selected = "chevreuil"),style = "margin-top:25px;"),
                        column(12),
                        column(width= 1,dateInput(inputId = "ani_date_arrivee", label = labelMandatory("Date d'arrivée"), value =  NA),style = "margin-top:25px;"),
                        bsTooltip("ani_date_arrivee", "Date d\\'arrivée de l\\'animal dans l\\'installation expériementale","bottom", options = list(container = "body")),
                        column(width= 1,dateInput(inputId = "ani_date_depart", label = "Date de départ", value = NA),style = "margin-top:25px;"),
                        bsTooltip("ani_date_depart", "Date de sortie de l\\'animal dans l\\'installation expériementale","bottom", options = list(container = "body")),
                        column(width= 1,textInput(inputId = "ani_code_sortie", label = "Code sortie"),style = "margin-top:25px;"),
                        bsTooltip("ani_code_sortie", "code de sortie de l\\'animal","bottom", options = list(container = "body")),
                        column(width= 2,textInput(inputId = "ani_raison_sortie", label = "Raison sortie"),style = "margin-top:25px;"),                       bsTooltip("ani_date_depart", "Date de sortie de l\\'animal dans l\\'installation expériementale","bottom", options = list(container = "body")),
                        bsTooltip("ani_raison_sortie", "raisons de la sortie de l\\'animal de l\\'installation expériementale","bottom", options = list(container = "body")),
                        column(width= 1,dateInput(inputId = "ani_date_mort", label = "Date mort", value =  NA),style = "margin-top:25px;"),
                        bsTooltip("ani_date_mort", "Date de la mort de l\\'animal","bottom", options = list(container = "body")),
                        column(width= 1,textInput(inputId = "ani_echantillon_genet", label = "Code Echant. genet"),style = "margin-top:25px;"),
                        bsTooltip("ani_echantillon_genet", "Code de l\\'échantillon pour la génétique","bottom", options = list(container = "body")),
                        column(width= 1,textInput(inputId = "ani_id_genotype", label = "Code génotype"),style = "margin-top:25px;"),
                        bsTooltip("ani_id_genotype", "Identifiant du génotype","bottom", options = list(container = "body")),
                        column(width= 2,textInput(inputId = "ani_remarque", label = "Remarque"),style = "margin-top:25px;"),
                        column(width= 1,textInput(inputId = "ani_transpondeur_id", label = "Code RFID"),style = "margin-top:25px;"),
                        bsTooltip("ani_transpondeur_id", "doit comporter 10 caractères ex.:	000786BE69","bottom", options = list(container = "body")),
                        column(width= 1,actionButton("subcol", "Enregistrer", class = "btn-primary"),style = "margin-top:25px;"),
                        bsTooltip("subcol", "les champs avec une * rouge doivent être remplis pour que le bouton soit actif","bottom", options = list(container = "body")),
                        column(width= 1,actionButton("new", "Effacer", class = "btn-primary"),style = "margin-top:30px;"),
                        bsTooltip("subcol", "Désélectionner l\\'animal en cours","bottom", options = list(container = "body")),
                        column(12),
                        column(width= 3,checkboxInput(inputId ="trie_ani_present",  label ="Ne conserver que les animaux présents actuellement dans l'installation.")),
                        column(2,p(class = 'text-center', downloadButton('downloadcsv2', 'Télécharger csv2'))),
                        bsTooltip("downloadcsv2", "Le format csv est un format texte dans lequel les séparateur de colonnes sont des ; et les séparteurs de décimale des ,","bottom", options = list(container = "body")),
                        column(2,p(class = 'text-center', downloadButton('downloadxlsx', 'Télécharger xlsx'))),
                        column(2,p(class = 'text-center', downloadButton('downloadhtml', 'Télécharger html'))),
                        #DT::DTOutput("mod_table")),
                        column(12),
                        DT::dataTableOutput("registre", width = 300)#, add_busy_bar(color = "red", height = "8px")
                                              ))
             #tabPanel("Suivi de consommation",  
                     # fluidRow(
                        # #column(width= 2,selectInput(inputId = "eqt_id_usuel_user", label = "N° du collier", choices = sort(as.numeric(dbGetQuery(con, "select distinct(eqt_id_usuel) from public.t_equipement_eqt")[,1])))),
                        # column(width= 1,uiOutput("colliers_existant")), ####here we test if you the list integrate the last collar entered before
                        # column(width= 1,numericInput(inputId = "eqc_annee_suivi", label = labelMandatory("Année de suivi"), value = annee, min = year(Sys.time()), max = 2025, step = 1)),
                        # column(width= 1,textInput(inputId = "eqc_drop_off", label = "N° de drop off")),
                        # column(width= 1,selectInput(inputId = "eqc_couleur_collier", label = "Couleur du collier",choices = append("",na.omit(dbGetQuery(con, "select distinct(eqc_couleur_collier) col_col from public.t_equipement_conf_eqc order by col_col")[,1])), selected = "", selectize = FALSE)),
                        # column(width= 1,selectInput(inputId = "eqc_couleur_boitier", label = "Couleur du boitier",choices = append("",na.omit(dbGetQuery(con, "select distinct(eqc_couleur_boitier) col_boi from public.t_equipement_conf_eqc order by col_boi")[,1])), selected = "", selectize = FALSE)), 
                        # column(width= 1,numericInput(inputId = "eqc_memoire", label = labelMandatory("Mémoire récepteur"), value = NULL, min = 1, max = 257)),
                        # column(width= 2,selectInput(inputId = "sen_association", label = labelMandatory("Capteurs associés"),choices = dbGetQuery(con, "select sen_association from listes.tr_sensors_sen order by sen_association DESC"))),
                        # column(width= 2,textInput(inputId = "eqc_remarque", label = "Remarque")),
                        # br(),
                        # column(width= 2,actionButton("subcolconf", "Submit", class = "btn-primary")),
                        # br(),
                        # column(width= 12,selectInput(inputId = "eqc_freq", label = "Recherche freq VHF",choices = append("",na.omit(dbGetQuery(con, "select distinct eqt_frequence freq from public.t_equipement_eqt order by eqt_frequence")[,1])), selected = "")),
                        # br(), br(),br(),
                        # DT::dataTableOutput("responsesconf", width = 300), tags$hr()
                     # ))
 
             ))

dbDisconnect(con)